from infrastructure.camera.synology_camera_source import SynologyCameraSource
from infrastructure.camera.onvif_camera_source import OnvifCameraSource
from infrastructure.camera.opencv_frame_reader import OpenCVFrameReader
