FROM python:3.12.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg libgl1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY domain/ domain/
COPY shared/ shared/
COPY infrastructure/ infrastructure/
COPY application/ application/
COPY interfaces/ interfaces/

CMD ["python", "-m", "interfaces.run_api", "--config", "/app/config.yaml"]
