FROM python:3.12.11-slim-bookworm

WORKDIR /app

COPY requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY domain/ domain/
COPY shared/ shared/
COPY infrastructure/ infrastructure/
COPY application/ application/
COPY interfaces/ interfaces/

CMD ["python", "-m", "interfaces.run_consumer", "--config", "/app/config.yaml"]
